version: '3.7'
services:

  db:
    container_name: db  
    image: postgres:alpine
    env_file:
      - ./core
    environment:
      POSTGRES_DB: ${DB_NAME}     
      POSTGRES_USER: ${DB_USER}     
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    depends_on:
      - db
  
  worker:
    build: .
    command: celery -A core worker --loglevel=info 
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
  
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
      - xpack.security.enabled=false 
    ports:
      - "9200:9200" 
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data 

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601" 
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  
    depends_on:
      - elasticsearch 

  backend:
    build: .
    container_name: "backend"
    command: gunicorn -b 0.0.0.0:8000 core.wsgi --timeout 60
    restart: "always"    
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./core
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
      - elasticsearch
      - kibana

  nginx:
    image: nginx
    container_name: nginx
    restart: "always" 
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - worker
      - elasticsearch
      - kibana
      - redis
      - db
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  elasticsearch_data: 