version: '3.7'

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: .
    command: celery -A core worker --loglevel=info 
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
  
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
      - xpack.security.enabled=false 
    ports:
      - "9200:9200" 
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data 

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601" 
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  
    depends_on:
      - elasticsearch 
  
  backend:
    build: .
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:8000
    restart: "always"    
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - elasticsearch
      - kibana
      - redis

volumes:
  elasticsearch_data: 