# Generated by Django 3.2.25 on 2025-03-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway_response",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
